name: Main branch to azure WebApp Deploy

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubunutu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        
      - name: Steup Node
        uses: actions/setup-node@v3
        with: 
          node-version: "20.x"
          
      - name: Install and Build
        run: |
          npm install
          npm run build
      
      - name: Zip build
        run: |
          zip release.zip ./* -r
      
      - name: Uploading the zipped Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: node-app
          path: release.zip
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Production'
      url: 'intelligatdemo-gufhhdefauc2ccac.centralindia-01.azurewebsites.net'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: intelligatdemo
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_75920E9CA45544EFA050A41226019426 }}
          package: .
