name: Build and deploy Node.js app to Azure Web App - intelligatdemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Node.js and cache
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Optimize for production
        run: |
          npm prune --production
          find . -type d \( -name ".git" -o -name ".github" -o -name "tests" -o -name "docs" \) -exec rm -rf {} + 2>/dev/null || true

      - name: Stop existing deployment (if any)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} || true
            az webapp deployment source disconnect --name intelligatdemo --resource-group intelligatdemo-rg || true
        continue-on-error: true

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'intelligatdemo'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_75920E9CA45544EFA050A41226019426 }}
          clean: true
          restart: true